# Generated by Django 5.0.7 on 2024-07-31 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=0, upload_to='pics/%y/%m/%d/'),
            preserve_default=False,
        ),
    ]
