# Generated by Django 5.0.7 on 2024-07-31 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='productName',
        ),
    ]
