# Generated by Django 5.0.7 on 2024-08-15 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_product_name_product_productname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
